ead:
  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'
  auth:
    jwtSecret: UTlZv+G8SZ2CV3oL9Kf3mmqeg00BnCos/LlJ9coXxNbqIiQZq/G2n4Yc9mvBBdasDGzUGXdeRDeqCNW7ze48CQEu4HRceZl7czmheAsnreE=
    jwtExpiration: 14400000

eureka:
  client:
    service-url:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost