server:
  port: 8080
  
spring:
  application:
    name: ead-api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: authuser-service
            uri: lb://EAD-AUTHUSER-SERVICE
            predicates:
              - Path=/ead-authuser/**
          - id: course-service
            uri: lb://EAD-COURSE-SERVICE
            predicates:
              - Path=/ead-course/**
          - id: notification-service
            uri: lb://EAD-NOTIFICATION-SERVICE
            predicates:
              - Path=/ead-notification/**
          - id: payment-service
            uri: lb://EAD-PAYMENT-SERVICE
            predicates:
              - Path=/ead-payment/**

# Configuração do Spring Actuator e Refresh Scope
management:
 endpoints:
   web:
     exposure:
       # Lista de endpoints expostos via web
       include:  
         # Endpoint para atualizar propriedades em runtime
         # Usado com @RefreshScope para recarregar beans sem restart
         # Endpoint: POST /actuator/refresh
         - refresh

         # Endpoint que retorna status da aplicação
         # Endpoint: GET /actuator/health  
         - health