server:
  port: 8086

spring:
  application:
    name: ead-payment-service

## configurações de propriedade do eureka client
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost